### PR TITLE
Split integration

### LINKED ISSUE #97: split integration tests in multiple parts
For example:
- testing-start
- blob-tests
- secret-tests
- certificate-tests
- testing-end

Implementation idea:
- before copying integration test to remote machine (`scp`), merge all local files
- iterate through space separated list of files and just append to temp file
- then upload this temp file with the same target file name as before

### LINKED ISSUE #109: errors not handling properly unhandled exceptions
This should just return inner exception.

```
azmi gettoken -e storagesd -j -i 017dc05c-4d12-4ac2-b5f8-5e239dc8bc54
azmi gettoken: [Azure.Identity.AuthenticationFailedException] The authentication request failed due to an unhandled exception.  See inner exception for details.
```

### LINKED ISSUE #110: update getsecret testing
Update key vault names to be pipeline variables, or at least base of the name and calculate other names

### PR DESCRIPTION
**Pull request by iricigor**
Integration test is split into 4 files:
- testing start
- blob testing
- secret testing
- testing end

Pipeline is updated to merge these files before running actual test.
List of files is also available as pipeline variable.

This resolves #110, resolves #109 and resolves #97.

### CODE REVIEW

File: test/integration/secret-tests.sh [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+#   this file is part of set of files!
+#
+
+
+#
+# setup variables
+#
+
+identity=$3
+KV_BASENAME=$4
```
Comment (iricigor) [inline test/integration/secret-tests.sh:13]: this resolves #110
