### PR TITLE
Small things

### LINKED ISSUE #62: small things
List of small things / house clean up tasks:
- [x] spell check: All Azure authentication is completely transparent VM user or for a running script.
- [x] simplify into one while: if (verbose) { while (ex.InnerException != null)... 
- [x] simplify listblobs loop to use Linq
- [x] remove HelpMessage class

### PR DESCRIPTION
**Pull request by iricigor**
Doing some house cleaning tasks, as specified in #62 

Resolves #62

### CODE REVIEW

File: src/azmi-commandline/azmi-commandline.cs [hunk 1]
```diff
@@ -225,13 +225,10 @@ private static void DisplayError(string subCommand, Exception ex, bool verbose)
             var oldColor = Console.ForegroundColor;
             Console.ForegroundColor = ConsoleColor.Red;
             Console.Error.WriteLine($"azmi {subCommand}: {ex.Message}");
-            if (verbose)
+            while (verbose && ex.InnerException != null)
```
Comment (iricigor) [inline src/azmi-commandline/azmi-commandline.cs]: Check this :)

File: src/azmi-main/Operations.cs [hunk 2]
```diff
@@ -63,15 +64,10 @@ public static string listBlobs(string containerUri, string identity = null, stri
...
-
+            
             try
             {
-                foreach (var blob in containerClient.GetBlobs(prefix: prefix))
-                {
-                    blobNamesList.Add(blob.Name);
-                }
-
+                var blobNamesList = containerClient.GetBlobs(prefix: prefix).Select(i => i.Name).ToList();
```
Comment (iricigor) [inline src/azmi-main/Operations.cs]: Check this even more :)

**Comment by iricigor** [comment]
[Build](https://skype.visualstudio.com/SCC/_build/results?buildId=27198416) and [Integration tests](https://skype.visualstudio.com/SCC/_build/results?buildId=27198437&view=ms.vss-test-web.build-test-results-tab) are OK.
